### ISSUE TITLE
Sized Constraint

### ISSUE THREAD

**Issue by PSeitz** [fereidani/rclite#4]
This crate requires `Sized`.
The std `Arc` does not have a size constraint, which is a quite common requirement when using `Arc<dyn MyTrait>`
```rust 
pub struct Arc<T>where
    T: ?Sized{ /* private fields */ }
```

**Comment by fereidani** [comment]
Hi, yes as I explained in README currently RcLite does not provide support for DSTs it may change in the future but currently, I have no plan for adding it.
